#-------------------------------
# General Site Settings
title: Sheryl Hsu
#logo: logo.svg # You can add own logo.
description: Sheryl Hsu's Blog (Archived)


#-------------------------------
# Author Settings
author:
  name: Sheryl Hsu
  image: Front_Pagecopy.jpg
  say-hello: Hello, I’m <strong>Sheryl Hsu</strong>
  bio: Designs, talks, and writes about <strong>programming</strong>, <strong>Raspberry Pi</strong>, <strong>3D printing</strong>, and <strong>school</strong>. I share projects, tutorials, and experiences. Loves computer science, entrepreneurship, and music.


#-------------------------------
# Contact links
twitter: https://twitter.com/ # Add your Twitter handle
facebook: https://facebook.com/ # Add your Facebook handle
dribbble: https://dribbble.com/ # Add your Dribbble handle
instagram: https://instagram.com/ # Add your Instagram handle
pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: true # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
